CREATE DATABASE DB_PClinics;
GO

USE DB_PClinics;
GO

CREATE TABLE TBL_Clinica(
	IdClinica INT PRIMARY KEY IDENTITY (1,1),
	CNPJ VARCHAR(14) NOT NULL,
	Endereco VARCHAR(500) NOT NULL
);

CREATE TABLE TBL_Cliente(
	IdCliente INT PRIMARY KEY IDENTITY (1,1),
	NomeCliente VARCHAR(200) NOT NULL
);

CREATE TABLE TBL_TipoPet(
	IdTipoPet INT PRIMARY KEY IDENTITY (1,1),
	TituloPet VARCHAR (200) NOT NULL
);

CREATE TABLE TBL_Raca(
	IdRaca INT PRIMARY KEY IDENTITY (1,1),
	TituloRaca VARCHAR(200) NOT NULL,
	FK_IdTipoPet INT FOREIGN KEY REFERENCES TBL_TipoPet(IdTipoPet) NOT NULL
);

CREATE TABLE TBL_Veterinario(
	IdVeterinario INT PRIMARY KEY IDENTITY (1,1),
	NomeVeterinario VARCHAR(200) NOT NULL,
	CRMV VARCHAR(5) NOT NULL,
	FK_IdClinica INT FOREIGN KEY REFERENCES TBL_Clinica(IdClinica) NOT NULL
);

CREATE TABLE TBL_Pet(
	IdPet INT PRIMARY KEY IDENTITY (1,1),
	NomePet VARCHAR(200) NOT NULL,
	Telefone VARCHAR(11) NOT NULL,
	FK_IdCliente INT FOREIGN KEY REFERENCES TBL_Cliente(IdCliente) NOT NULL,
	FK_IdRaca INT FOREIGN KEY REFERENCES TBL_Raca(IdRaca) NOT NULL
);

CREATE TABLE TBL_Atendimento(
	IdAtendimento INT PRIMARY KEY IDENTITY(1,1),
	DataAtendimento DATE NOT NULL,
	Descricao VARCHAR(1000),
	FK_IdVeterinario INT FOREIGN KEY REFERENCES TBL_Veterinario(IdVeterinario) NOT NULL,
	FK_IdPet INT FOREIGN KEY REFERENCES TBL_Pet(IdPet) NOT NULL
);