USE master;
GO

CREATE DATABASE DB_RoteiroLivros;
GO

USE DB_RoteiroLivros;
GO

CREATE TABLE TblGenero(
	IdGenero INT PRIMARY KEY IDENTITY (1, 1),
	Nome VARCHAR(200) NOT NULL
);

CREATE TABLE TblAutor(
	IdAutor INT PRIMARY KEY IDENTITY(1,1),
	NomeAutor VARCHAR(200) NOT NULL
);

CREATE TABLE TblLivro(
	IdLivro INT PRIMARY KEY IDENTITY (1,1),
	Titulo VARCHAR(200) NOT NULL,
	FKIdGenero INT FOREIGN KEY REFERENCES TblGenero (IdGenero),
	FKIdAutor INT FOREIGN KEY REFERENCES TblAutor (IdAutor)
);
